AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Application Load Balancer Stack for Multi-Service Platform.
  Creates an internal ALB with HTTP/HTTPS listeners. Default action returns 404.
  Per-project listener rules are added by project.yaml stacks.

# =============================================================================
# METADATA
# =============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - PrivateSubnet1Id
          - PrivateSubnet2Id
          - AlbSecurityGroupId
    ParameterLabels:
      Environment:
        default: "Deployment Environment"
      ProjectName:
        default: "Project Name"
      VpcId:
        default: "VPC ID"
      PrivateSubnet1Id:
        default: "Private Subnet 1 ID"
      PrivateSubnet2Id:
        default: "Private Subnet 2 ID"
      AlbSecurityGroupId:
        default: "ALB Security Group ID"

# =============================================================================
# PARAMETERS
# =============================================================================
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: Must be dev, staging, or prod

  ProjectName:
    Type: String
    Description: Project name used for resource naming
    Default: japfa-api
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 32
    ConstraintDescription: Must be lowercase alphanumeric with hyphens, 3-32 characters

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the ALB will be deployed

  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1 ID for ALB deployment (AZ-a)

  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2 ID for ALB deployment (AZ-b)

  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the ALB

# =============================================================================
# CONDITIONS
# =============================================================================
Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  IsStaging: !Equals [!Ref Environment, staging]
  IsDevelopment: !Equals [!Ref Environment, dev]
  # Use HTTPS only for staging and production
  UseHttps: !Or
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref Environment, staging]

# =============================================================================
# RESOURCES
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # Internal Application Load Balancer
  # Requirement 2.3: ALB deployed in private subnets, not directly accessible
  # from the internet
  # ---------------------------------------------------------------------------
  InternalAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-alb
      Scheme: internal
      Type: application
      IpAddressType: ipv4
      Subnets:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"
        - Key: idle_timeout.timeout_seconds
          Value: "60"
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: "true"
        - Key: routing.http2.enabled
          Value: "true"
        - Key: access_logs.s3.enabled
          Value: "false"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alb
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Internal Application Load Balancer

  # ---------------------------------------------------------------------------
  # HTTP Listener
  # For dev: returns fixed 404 by default (projects add their own rules)
  # For staging/prod: redirects to HTTPS
  # ---------------------------------------------------------------------------
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref InternalAlb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - !If
          - UseHttps
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: "443"
              StatusCode: HTTP_301
          - Type: fixed-response
            FixedResponseConfig:
              StatusCode: "404"
              ContentType: application/json
              MessageBody: '{"error":"Not Found","message":"No service registered for this path"}'

  # ---------------------------------------------------------------------------
  # HTTPS Listener with TLS 1.3 Policy (staging/prod only)
  # Uses ELBSecurityPolicy-TLS13-1-2-2021-06 for TLS 1.3 support
  # Note: For internal ALB, we use a self-signed certificate or ACM certificate
  # ---------------------------------------------------------------------------
  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: UseHttps
    Properties:
      LoadBalancerArn: !Ref InternalAlb
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: "404"
            ContentType: application/json
            MessageBody: '{"error":"Not Found","message":"No service registered for this path"}'

  # ---------------------------------------------------------------------------
  # ACM Certificate for Internal ALB (staging/prod only)
  # Self-signed certificate for internal use
  # In production, this should be replaced with a proper ACM certificate
  # ---------------------------------------------------------------------------
  AlbCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: UseHttps
    Properties:
      DomainName: !Sub ${ProjectName}-${Environment}.internal
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alb-cert
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  # ALB Outputs
  AlbArn:
    Description: Application Load Balancer ARN
    Value: !Ref InternalAlb
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AlbArn

  AlbDnsName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt InternalAlb.DNSName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AlbDnsName

  AlbFullName:
    Description: Application Load Balancer Full Name
    Value: !GetAtt InternalAlb.LoadBalancerFullName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AlbFullName

  AlbHostedZoneId:
    Description: Application Load Balancer Hosted Zone ID
    Value: !GetAtt InternalAlb.CanonicalHostedZoneID
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AlbHostedZoneId

  # Listener Outputs
  HttpListenerArn:
    Description: HTTP Listener ARN
    Value: !Ref HttpListener
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HttpListenerArn

  HttpsListenerArn:
    Condition: UseHttps
    Description: HTTPS Listener ARN
    Value: !Ref HttpsListener
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HttpsListenerArn

  # Certificate Output
  CertificateArn:
    Condition: UseHttps
    Description: ACM Certificate ARN
    Value: !Ref AlbCertificate
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AlbCertificateArn

