AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Service Stack for CI/CD Pipeline.
  Creates an ECS Fargate service with rolling deployment, circuit breaker,
  ALB target group registration, and auto-scaling configuration.
  Requirements: 6.2 (rolling deployment), 6.3 (maintain healthy tasks),
  6.4 (rollback on failure), 6.6 (ALB registration)

# =============================================================================
# METADATA
# =============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: "Network Configuration"
        Parameters:
          - PrivateSubnet1Id
          - PrivateSubnet2Id
          - EcsSecurityGroupId
      - Label:
          default: "ECS Configuration"
        Parameters:
          - EcsClusterArn
          - TaskDefinitionArn
          - ContainerName
          - ContainerPort
      - Label:
          default: "Load Balancer Configuration"
        Parameters:
          - TargetGroupArn
      - Label:
          default: "Service Configuration"
        Parameters:
          - DesiredCount
          - MinimumHealthyPercent
          - MaximumPercent
          - HealthCheckGracePeriodSeconds
      - Label:
          default: "Auto Scaling Configuration"
        Parameters:
          - MinCapacity
          - MaxCapacity
          - CpuTargetValue
          - MemoryTargetValue
          - ScaleInCooldown
          - ScaleOutCooldown
      - Label:
          default: "Cost Tracking Configuration"
        Parameters:
          - ComputeType
    ParameterLabels:
      Environment:
        default: "Deployment Environment"
      ProjectName:
        default: "Project Name"
      PrivateSubnet1Id:
        default: "Private Subnet 1 ID"
      PrivateSubnet2Id:
        default: "Private Subnet 2 ID"
      EcsSecurityGroupId:
        default: "ECS Security Group ID"
      EcsClusterArn:
        default: "ECS Cluster ARN"
      TaskDefinitionArn:
        default: "Task Definition ARN"
      ContainerName:
        default: "Container Name"
      ContainerPort:
        default: "Container Port"
      TargetGroupArn:
        default: "ALB Target Group ARN"
      DesiredCount:
        default: "Desired Task Count"
      MinimumHealthyPercent:
        default: "Minimum Healthy Percent"
      MaximumPercent:
        default: "Maximum Percent"
      HealthCheckGracePeriodSeconds:
        default: "Health Check Grace Period (seconds)"
      MinCapacity:
        default: "Minimum Capacity"
      MaxCapacity:
        default: "Maximum Capacity"
      CpuTargetValue:
        default: "CPU Target Utilization (%)"
      MemoryTargetValue:
        default: "Memory Target Utilization (%)"
      ScaleInCooldown:
        default: "Scale In Cooldown (seconds)"
      ScaleOutCooldown:
        default: "Scale Out Cooldown (seconds)"
      ComputeType:
        default: "Compute Type for Cost Tracking"

# =============================================================================
# PARAMETERS
# =============================================================================
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: Must be dev, staging, or prod

  ProjectName:
    Type: String
    Description: Project name used for resource naming
    Default: japfa-api
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 32
    ConstraintDescription: Must be lowercase alphanumeric with hyphens, 3-32 characters

  # Network Configuration
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1 ID for ECS tasks (AZ-a)

  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2 ID for ECS tasks (AZ-b)

  EcsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for ECS tasks

  # ECS Configuration
  EcsClusterArn:
    Type: String
    Description: ARN of the ECS Cluster
    AllowedPattern: ^arn:aws:ecs:[a-z0-9-]+:[0-9]+:cluster\/[a-zA-Z0-9_-]+$
    ConstraintDescription: Must be a valid ECS Cluster ARN

  TaskDefinitionArn:
    Type: String
    Description: ARN of the ECS Task Definition
    AllowedPattern: ^arn:aws:ecs:[a-z0-9-]+:[0-9]+:task-definition\/[a-zA-Z0-9_-]+:[0-9]+$
    ConstraintDescription: Must be a valid ECS Task Definition ARN

  ContainerName:
    Type: String
    Description: Name of the container in the task definition
    Default: japfa-api-dev
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 64
    ConstraintDescription: Must be lowercase alphanumeric with hyphens

  ContainerPort:
    Type: Number
    Description: Port exposed by the container
    Default: 8080
    MinValue: 1
    MaxValue: 65535
    ConstraintDescription: Must be a valid port number (1-65535)

  # Load Balancer Configuration
  TargetGroupArn:
    Type: String
    Description: ARN of the ALB Target Group
    AllowedPattern: ^arn:aws:elasticloadbalancing:[a-z0-9-]+:[0-9]+:targetgroup\/[a-zA-Z0-9-]+\/[a-z0-9]+$
    ConstraintDescription: Must be a valid ALB Target Group ARN

  # Service Configuration
  DesiredCount:
    Type: Number
    Description: Desired number of tasks to run
    Default: 2
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: Must be between 0 and 100

  MinimumHealthyPercent:
    Type: Number
    Description: >
      Minimum healthy percent during deployment. Set to 50% to allow
      zero-downtime deployments with at least one healthy task.
    Default: 50
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: Must be between 0 and 100

  MaximumPercent:
    Type: Number
    Description: >
      Maximum percent of tasks during deployment. Set to 200% to allow
      double the desired count during rolling updates.
    Default: 200
    MinValue: 100
    MaxValue: 400
    ConstraintDescription: Must be between 100 and 400

  HealthCheckGracePeriodSeconds:
    Type: Number
    Description: >
      Seconds to wait before starting health checks on new tasks.
      Allows time for container startup and initialization.
    Default: 60
    MinValue: 0
    MaxValue: 2147483647
    ConstraintDescription: Must be a non-negative integer

  # Auto Scaling Configuration
  MinCapacity:
    Type: Number
    Description: Minimum number of tasks for auto-scaling
    Default: 2
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: Must be between 0 and 100

  MaxCapacity:
    Type: Number
    Description: Maximum number of tasks for auto-scaling
    Default: 10
    MinValue: 1
    MaxValue: 100
    ConstraintDescription: Must be between 1 and 100

  CpuTargetValue:
    Type: Number
    Description: Target CPU utilization percentage for auto-scaling
    Default: 70
    MinValue: 1
    MaxValue: 100
    ConstraintDescription: Must be between 1 and 100

  MemoryTargetValue:
    Type: Number
    Description: Target memory utilization percentage for auto-scaling
    Default: 80
    MinValue: 1
    MaxValue: 100
    ConstraintDescription: Must be between 1 and 100

  ScaleInCooldown:
    Type: Number
    Description: Cooldown period (seconds) after scale-in before another scale-in
    Default: 300
    MinValue: 0
    MaxValue: 3600
    ConstraintDescription: Must be between 0 and 3600 seconds

  ScaleOutCooldown:
    Type: Number
    Description: Cooldown period (seconds) after scale-out before another scale-out
    Default: 60
    MinValue: 0
    MaxValue: 3600
    ConstraintDescription: Must be between 0 and 3600 seconds

  ComputeType:
    Type: String
    Description: Compute type for cost allocation tagging (fargate or ec2)
    Default: fargate
    AllowedValues:
      - fargate
      - ec2
    ConstraintDescription: Must be fargate or ec2

# =============================================================================
# CONDITIONS
# =============================================================================
Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  IsStaging: !Equals [!Ref Environment, staging]
  IsDevelopment: !Equals [!Ref Environment, dev]

# =============================================================================
# RESOURCES
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # ECS Service
  # Purpose: Manages the deployment and scaling of ECS tasks
  # Requirement 6.2: WHEN the Task_Definition is updated, THE ECS_Fargate
  #                  SHALL perform a rolling deployment
  # Requirement 6.3: WHILE deployment is in progress, THE ECS_Fargate SHALL
  #                  maintain at least one healthy task running
  # Requirement 6.4: WHEN a new task fails health checks, THE ECS_Fargate
  #                  SHALL roll back to the previous task definition
  # Requirement 6.6: THE ECS_Fargate SHALL register healthy tasks with the
  #                  ALB target group
  # ---------------------------------------------------------------------------
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-${Environment}-service
      Cluster: !Ref EcsClusterArn
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: !Ref DesiredCount
      # Fargate launch type for serverless container execution
      LaunchType: FARGATE
      # Use latest Fargate platform version for newest features and patches
      PlatformVersion: LATEST
      # Network configuration for awsvpc network mode
      # Requirement 6.8: ECS service deployed in private subnets with NAT Gateway
      NetworkConfiguration:
        AwsvpcConfiguration:
          # DISABLED: Tasks in private subnets use NAT Gateway for outbound
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
          SecurityGroups:
            - !Ref EcsSecurityGroupId
      # Load balancer configuration
      # Requirement 6.6: Register healthy tasks with ALB target group
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn
      # Deployment configuration for rolling updates
      # Requirement 6.2: Rolling deployment when task definition is updated
      # Requirement 6.3: Maintain at least one healthy task (MinimumHealthyPercent: 50%)
      # Requirement 6.4: Circuit breaker with automatic rollback on failure
      DeploymentConfiguration:
        # MinimumHealthyPercent: 50% ensures at least one task remains healthy
        # during deployment when DesiredCount is 2
        MinimumHealthyPercent: !Ref MinimumHealthyPercent
        # MaximumPercent: 200% allows up to double the tasks during deployment
        MaximumPercent: !Ref MaximumPercent
        # Deployment circuit breaker for automatic rollback
        # Requirement 6.4: Roll back to previous task definition on health check failure
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      # Health check grace period allows time for container startup
      # before ECS starts checking task health
      HealthCheckGracePeriodSeconds: !Ref HealthCheckGracePeriodSeconds
      # Enable ECS Exec for debugging and troubleshooting
      # Allows running commands inside containers via AWS CLI
      EnableExecuteCommand: true
      # Enable ECS managed tags for cost allocation
      EnableECSManagedTags: true
      # Propagate tags from service to tasks
      PropagateTags: SERVICE
      # Scheduling strategy for Fargate (REPLICA is the only option)
      SchedulingStrategy: REPLICA
      # Deployment controller type
      DeploymentController:
        Type: ECS
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-service
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: ECS Fargate Service for API
        - Key: ManagedBy
          Value: CloudFormation
        # Requirement 3.2: ComputeType tag for cost tracking
        - Key: ComputeType
          Value: !Ref ComputeType

  # ---------------------------------------------------------------------------
  # Auto Scaling Target
  # Purpose: Defines the scalable dimension for the ECS service
  # Allows Application Auto Scaling to adjust the desired count
  # ---------------------------------------------------------------------------
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: EcsService
    Properties:
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      ResourceId: !Sub
        - service/${ClusterName}/${ServiceName}
        - ClusterName: !Select [1, !Split ["/", !Ref EcsClusterArn]]
          ServiceName: !GetAtt EcsService.Name
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # ---------------------------------------------------------------------------
  # CPU-Based Auto Scaling Policy
  # Purpose: Scales the service based on average CPU utilization
  # Target: 70% CPU utilization (configurable)
  # ---------------------------------------------------------------------------
  CpuScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-${Environment}-cpu-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: !Ref CpuTargetValue
        # Cooldown periods prevent rapid scaling oscillations
        ScaleInCooldown: !Ref ScaleInCooldown
        ScaleOutCooldown: !Ref ScaleOutCooldown
        # Disable scale-in to prevent aggressive scale-down (optional)
        # DisableScaleIn: false

  # ---------------------------------------------------------------------------
  # Memory-Based Auto Scaling Policy
  # Purpose: Scales the service based on average memory utilization
  # Target: 80% memory utilization (configurable)
  # ---------------------------------------------------------------------------
  MemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-${Environment}-memory-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: !Ref MemoryTargetValue
        # Cooldown periods prevent rapid scaling oscillations
        ScaleInCooldown: !Ref ScaleInCooldown
        ScaleOutCooldown: !Ref ScaleOutCooldown

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  # Service Outputs
  ServiceArn:
    Description: ECS Service ARN
    Value: !Ref EcsService
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ServiceArn

  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt EcsService.Name
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ServiceName

  # Deployment Configuration Outputs
  MinimumHealthyPercent:
    Description: Minimum healthy percent during deployment
    Value: !Ref MinimumHealthyPercent
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MinimumHealthyPercent

  MaximumPercent:
    Description: Maximum percent during deployment
    Value: !Ref MaximumPercent
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MaximumPercent

  DeploymentCircuitBreakerEnabled:
    Description: Whether deployment circuit breaker is enabled
    Value: "true"
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CircuitBreakerEnabled

  DeploymentRollbackEnabled:
    Description: Whether automatic rollback is enabled
    Value: "true"
    Export:
      Name: !Sub ${ProjectName}-${Environment}-RollbackEnabled

  # Auto Scaling Outputs
  AutoScalingTargetId:
    Description: Auto Scaling Target ID
    Value: !Ref AutoScalingTarget
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AutoScalingTargetId

  MinCapacity:
    Description: Minimum capacity for auto-scaling
    Value: !Ref MinCapacity
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MinCapacity

  MaxCapacity:
    Description: Maximum capacity for auto-scaling
    Value: !Ref MaxCapacity
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MaxCapacity

  CpuScalingPolicyArn:
    Description: CPU-based scaling policy ARN
    Value: !Ref CpuScalingPolicy
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CpuScalingPolicyArn

  MemoryScalingPolicyArn:
    Description: Memory-based scaling policy ARN
    Value: !Ref MemoryScalingPolicy
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MemoryScalingPolicyArn

  CpuTargetUtilization:
    Description: Target CPU utilization for auto-scaling
    Value: !Ref CpuTargetValue
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CpuTargetUtilization

  MemoryTargetUtilization:
    Description: Target memory utilization for auto-scaling
    Value: !Ref MemoryTargetValue
    Export:
      Name: !Sub ${ProjectName}-${Environment}-MemoryTargetUtilization

  # Network Configuration Outputs
  ServiceSubnets:
    Description: Subnets where the service tasks are deployed
    Value: !Sub "${PrivateSubnet1Id},${PrivateSubnet2Id}"
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ServiceSubnets

  ServiceSecurityGroup:
    Description: Security group for the service tasks
    Value: !Ref EcsSecurityGroupId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ServiceSecurityGroup

  # Health Check Configuration
  HealthCheckGracePeriod:
    Description: Health check grace period in seconds
    Value: !Ref HealthCheckGracePeriodSeconds
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HealthCheckGracePeriod

  # Execute Command Status
  ExecuteCommandEnabled:
    Description: Whether ECS Exec is enabled for debugging
    Value: "true"
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ExecuteCommandEnabled

  # Service Configuration Summary
  ServiceConfigurationSummary:
    Description: Summary of service configuration
    Value: !Sub |
      Service: ${ProjectName}-${Environment}-service
      Cluster: ${EcsClusterArn}
      Desired Count: ${DesiredCount}
      Min Healthy: ${MinimumHealthyPercent}%
      Max Percent: ${MaximumPercent}%
      Circuit Breaker: Enabled with Rollback
      Auto Scaling: ${MinCapacity}-${MaxCapacity} tasks
      CPU Target: ${CpuTargetValue}%
      Memory Target: ${MemoryTargetValue}%
