AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Shared Infrastructure Stack for Multi-Service Platform.
  Deploys VPC, security groups, IAM roles, ALB, API Gateway, ECS Cluster,
  and monitoring. Per-project resources (ECR, pipelines, services) are
  deployed separately via project.yaml.

# =============================================================================
# METADATA
# =============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: "Cost Tracking Configuration"
        Parameters:
          - ComputeType
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcCidr
      - Label:
          default: "Nested Stack Configuration"
        Parameters:
          - TemplatesBucketName
          - TemplatesBucketPrefix
    ParameterLabels:
      Environment:
        default: "Deployment Environment"
      ProjectName:
        default: "Project Name"
      ComputeType:
        default: "Compute Type for Cost Tracking"
      VpcCidr:
        default: "VPC CIDR Block"
      TemplatesBucketName:
        default: "S3 Bucket for Nested Templates"
      TemplatesBucketPrefix:
        default: "S3 Prefix for Nested Templates"

# =============================================================================
# PARAMETERS
# =============================================================================
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: Must be dev, staging, or prod

  ProjectName:
    Type: String
    Description: Project name used for resource naming (lowercase, alphanumeric, hyphens only)
    Default: japfa-api
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 32
    ConstraintDescription: Must be lowercase alphanumeric with hyphens, 3-32 characters

  ComputeType:
    Type: String
    Description: Compute type for cost allocation tagging (fargate for this template)
    Default: fargate
    AllowedValues:
      - fargate
      - ec2
    ConstraintDescription: Must be fargate or ec2

  VpcCidr:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block (e.g., 10.0.0.0/16)

  TemplatesBucketName:
    Type: String
    Description: S3 bucket name containing nested CloudFormation templates
    MinLength: 3
    MaxLength: 63

  TemplatesBucketPrefix:
    Type: String
    Description: S3 prefix (folder path) for nested templates
    Default: infrastructure
    MaxLength: 256

  CustomDomainName:
    Type: String
    Description: Custom domain name for the API Gateway (e.g., api.my-company.com.vn). Leave empty to skip.
    Default: ""

  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for the custom domain. Required if CustomDomainName is set.
    Default: ""

# =============================================================================
# CONDITIONS
# =============================================================================
Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  IsStaging: !Equals [!Ref Environment, staging]
  IsDevelopment: !Equals [!Ref Environment, dev]

# =============================================================================
# RESOURCES - SHARED INFRASTRUCTURE STACKS
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # VPC and Networking Stack
  # ---------------------------------------------------------------------------
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/vpc.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-vpc-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ---------------------------------------------------------------------------
  # Security Groups Stack
  # ---------------------------------------------------------------------------
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-security-groups-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ---------------------------------------------------------------------------
  # IAM Roles and Policies Stack
  # ---------------------------------------------------------------------------
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/iam.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-iam-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ---------------------------------------------------------------------------
  # Application Load Balancer Stack
  # ---------------------------------------------------------------------------
  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/alb.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        AlbSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.AlbSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alb-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ---------------------------------------------------------------------------
  # API Gateway Stack
  # ---------------------------------------------------------------------------
  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - SecurityGroupsStack
      - AlbStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/api-gateway.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        VpcLinkSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.VpcLinkSecurityGroupId
        AlbListenerArn: !GetAtt AlbStack.Outputs.HttpListenerArn
        AlbDnsName: !GetAtt AlbStack.Outputs.AlbDnsName
        CustomDomainName: !Ref CustomDomainName
        CertificateArn: !Ref CertificateArn
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-api-gateway-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ---------------------------------------------------------------------------
  # ECS Cluster Stack
  # ---------------------------------------------------------------------------
  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/ecs-cluster.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        ComputeType: !Ref ComputeType
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-ecs-cluster-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ComputeType
          Value: !Ref ComputeType

  # ---------------------------------------------------------------------------
  # Monitoring and Observability Stack
  # ---------------------------------------------------------------------------
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EcsClusterStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${TemplatesBucketPrefix}/monitoring.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-monitoring-stack
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  Environment:
    Description: Deployment environment
    Value: !Ref Environment

  ProjectName:
    Description: Project name
    Value: !Ref ProjectName

  ComputeType:
    Description: Compute type for cost allocation (fargate or ec2)
    Value: !Ref ComputeType

  # VPC Outputs
  VpcId:
    Description: VPC ID
    Value: !GetAtt VpcStack.Outputs.VpcId

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !GetAtt VpcStack.Outputs.PublicSubnet1Id

  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !GetAtt VpcStack.Outputs.PublicSubnet2Id

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !GetAtt VpcStack.Outputs.PrivateSubnet1Id

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !GetAtt VpcStack.Outputs.PrivateSubnet2Id

  # API Gateway Outputs
  ApiGatewayEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiGatewayStack.Outputs.ApiGatewayEndpoint

  ApiGatewayId:
    Description: API Gateway ID
    Value: !GetAtt ApiGatewayStack.Outputs.ApiGatewayId

  # ALB Outputs
  AlbDnsName:
    Description: Application Load Balancer DNS name
    Value: !GetAtt AlbStack.Outputs.AlbDnsName

  AlbArn:
    Description: Application Load Balancer ARN
    Value: !GetAtt AlbStack.Outputs.AlbArn

  # ECS Cluster Outputs
  EcsClusterArn:
    Description: ECS Cluster ARN
    Value: !GetAtt EcsClusterStack.Outputs.ClusterArn

  EcsClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt EcsClusterStack.Outputs.ClusterName

  # Monitoring Outputs
  NotificationTopicArn:
    Description: SNS Notification Topic ARN
    Value: !GetAtt MonitoringStack.Outputs.NotificationTopicArn

  DashboardName:
    Description: CloudWatch Dashboard Name
    Value: !GetAtt MonitoringStack.Outputs.DashboardName

