AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Secrets Manager Stack for CI/CD Pipeline.
  Creates secret placeholders for Azure DevOps PAT and database connection strings.
  Secrets are created as placeholders that should be populated manually after deployment.
  Requirements: 1.2 (PAT in Secrets Manager), 8.1 (retrieve PAT at runtime), 8.2 (database credentials)

# =============================================================================
# METADATA
# =============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: "Secret Rotation Configuration (Optional)"
        Parameters:
          - EnableSecretRotation
          - RotationScheduleDays
    ParameterLabels:
      Environment:
        default: "Deployment Environment"
      ProjectName:
        default: "Project Name"
      EnableSecretRotation:
        default: "Enable Secret Rotation"
      RotationScheduleDays:
        default: "Rotation Schedule (Days)"

# =============================================================================
# PARAMETERS
# =============================================================================
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: Must be dev, staging, or prod

  ProjectName:
    Type: String
    Description: Project name used for resource naming
    Default: japfa-api
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 32
    ConstraintDescription: Must be lowercase alphanumeric with hyphens, 3-32 characters

  EnableSecretRotation:
    Type: String
    Description: Enable automatic secret rotation (requires Lambda rotation function)
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  RotationScheduleDays:
    Type: Number
    Description: Number of days between automatic secret rotations
    Default: 30
    MinValue: 1
    MaxValue: 365

# =============================================================================
# CONDITIONS
# =============================================================================
Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  RotationEnabled: !Equals [!Ref EnableSecretRotation, "true"]

# =============================================================================
# RESOURCES
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # Azure DevOps PAT Secret
  # Purpose: Stores the Personal Access Token for authenticating with Azure DevOps
  # Usage: Retrieved by CodeBuild at runtime to clone the repository
  # Requirements: 1.2 (PAT in Secrets Manager), 8.1 (retrieve PAT at runtime)
  # ---------------------------------------------------------------------------
  AzureDevOpsPatSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}/${Environment}/azure-devops-pat
      Description: >
        Azure DevOps Personal Access Token (PAT) for repository authentication.
        This secret should be manually populated after stack deployment.
        Required permissions: Code (Read) for the target repository.
      # Placeholder secret value - MUST be updated manually after deployment
      SecretString: !Sub |
        {
          "pat": "PLACEHOLDER_UPDATE_AFTER_DEPLOYMENT",
          "organization": "your-organization",
          "project": "your-project",
          "repository": "your-repository",
          "description": "PAT for ${ProjectName} ${Environment} CI/CD pipeline"
        }
      KmsKeyId: alias/aws/secretsmanager
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-azure-devops-pat
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Azure DevOps PAT Authentication
        - Key: SecretType
          Value: SourceControl
        - Key: RequiresManualUpdate
          Value: "true"

  # ---------------------------------------------------------------------------
  # Database Connection Strings Secret
  # Purpose: Stores database connection strings for the application
  # Usage: Injected into ECS tasks as environment variables at runtime
  # Requirements: 8.2 (database credentials in Secrets Manager)
  # Structure: Contains connection strings for PoultrySale and MasterDb databases
  # ---------------------------------------------------------------------------
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}/${Environment}/db/connection-strings
      Description: >
        Database connection strings for the application.
        This secret should be manually populated after stack deployment.
        Contains connection strings for PoultrySale and MasterDb databases.
      # Placeholder secret value - MUST be updated manually after deployment
      SecretString: !Sub |
        {
          "ConnectionStrings__PoultrySale": "Server=PLACEHOLDER;Database=PoultrySale;User Id=PLACEHOLDER;Password=PLACEHOLDER;TrustServerCertificate=True;",
          "ConnectionStrings__MasterDb": "Server=PLACEHOLDER;Database=MasterDb;User Id=PLACEHOLDER;Password=PLACEHOLDER;TrustServerCertificate=True;",
          "description": "Database connection strings for ${ProjectName} ${Environment}"
        }
      KmsKeyId: alias/aws/secretsmanager
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-connection-strings
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Database Connection Strings
        - Key: SecretType
          Value: Database
        - Key: RequiresManualUpdate
          Value: "true"

  # ---------------------------------------------------------------------------
  # Resource Policy for Azure DevOps PAT Secret
  # Purpose: Restricts access to the PAT secret to only CodeBuild service role
  # Security: Implements least-privilege access control
  # ---------------------------------------------------------------------------
  AzureDevOpsPatSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref AzureDevOpsPatSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeBuildAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalTag/Purpose: CodeBuild Service Role
          - Sid: DenyUnencryptedAccess
            Effect: Deny
            Principal: "*"
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

  # ---------------------------------------------------------------------------
  # Resource Policy for Database Secret
  # Purpose: Restricts access to database credentials to ECS execution role
  # Security: Implements least-privilege access control
  # ---------------------------------------------------------------------------
  DatabaseSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref DatabaseSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEcsExecutionRoleAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalTag/Purpose: ECS Task Execution Role
          - Sid: DenyUnencryptedAccess
            Effect: Deny
            Principal: "*"
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  # Azure DevOps PAT Secret Outputs
  AzureDevOpsPatSecretArn:
    Description: ARN of the Azure DevOps PAT secret for IAM policies and CodeBuild configuration
    Value: !Ref AzureDevOpsPatSecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AzureDevOpsPatSecretArn

  AzureDevOpsPatSecretName:
    Description: Name of the Azure DevOps PAT secret for reference
    Value: !Sub ${ProjectName}/${Environment}/azure-devops-pat
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AzureDevOpsPatSecretName

  # Database Secret Outputs
  DatabaseSecretArn:
    Description: ARN of the database connection strings secret for IAM policies and ECS task definition
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DatabaseSecretArn

  DatabaseSecretName:
    Description: Name of the database connection strings secret for reference
    Value: !Sub ${ProjectName}/${Environment}/db/connection-strings
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DatabaseSecretName

  # Post-Deployment Instructions
  PostDeploymentInstructions:
    Description: Instructions for updating secrets after deployment
    Value: !Sub |
      IMPORTANT: Update the following secrets with actual values after deployment:
      1. Azure DevOps PAT: aws secretsmanager put-secret-value --secret-id ${ProjectName}/${Environment}/azure-devops-pat --secret-string '{"pat":"YOUR_ACTUAL_PAT","organization":"your-org","project":"your-project","repository":"your-repo"}'
      2. Database Credentials: aws secretsmanager put-secret-value --secret-id ${ProjectName}/${Environment}/db/connection-strings --secret-string '{"ConnectionStrings__PoultrySale":"Server=...","ConnectionStrings__MasterDb":"Server=..."}'

