AWSTemplateFormatVersion: "2010-09-09"
Description: Task Definition for Per-Project Stack (Nested Stack).

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  ServiceName:
    Type: String
  ContainerCpu:
    Type: String
  ContainerMemory:
    Type: String
  ContainerPort:
    Type: Number
  ExecutionRoleArn:
    Type: String
  TaskRoleArn:
    Type: String
  PathBase:
    Type: String
  ContainerImage:
    Type: String

Resources:
  ServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ProjectName}-${Environment}-${ServiceName}
      RetentionInDays: 30

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-${Environment}-${ServiceName}
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-container
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ServiceLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ASPNETCORE_ENVIRONMENT
              Value: !Ref Environment
            - Name: SERVICE_NAME
              Value: !Ref ServiceName
            - Name: PATH_BASE
              Value: !Ref PathBase
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceName

Outputs:
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
